/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/users'
import { Route as UpdatepasswordImport } from './routes/updatepassword'
import { Route as SinginupdatepassswordImport } from './routes/singinupdatepasssword'
import { Route as SignUpImport } from './routes/signUp'
import { Route as SignInImport } from './routes/signIn'
import { Route as GetStatsImport } from './routes/getStats'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as CreateticketImport } from './routes/createticket'
import { Route as UpdateticketTicketIdImport } from './routes/updateticket/$ticket-id'
import { Route as PostsIdImport } from './routes/posts/$id'
import { Route as GetsingleticketTicketIdImport } from './routes/getsingleticket/$ticket-id'
import { Route as GetfilesTicketIdImport } from './routes/getfiles/$ticket-id'
import { Route as GetallcommentsTicketIdImport } from './routes/getallcomments/$ticket-id'
import { Route as FileuploadTicketIdImport } from './routes/fileupload/$ticket-id'
import { Route as AssignticketsTicketIdImport } from './routes/assigntickets/$ticket-id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const UpdatepasswordRoute = UpdatepasswordImport.update({
  id: '/updatepassword',
  path: '/updatepassword',
  getParentRoute: () => rootRoute,
} as any)

const SinginupdatepassswordRoute = SinginupdatepassswordImport.update({
  id: '/singinupdatepasssword',
  path: '/singinupdatepasssword',
  getParentRoute: () => rootRoute,
} as any)

const SignUpRoute = SignUpImport.update({
  id: '/signUp',
  path: '/signUp',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRoute,
} as any)

const GetStatsRoute = GetStatsImport.update({
  id: '/getStats',
  path: '/getStats',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const CreateticketRoute = CreateticketImport.update({
  id: '/createticket',
  path: '/createticket',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const UpdateticketTicketIdRoute = UpdateticketTicketIdImport.update({
  id: '/updateticket/$ticket-id',
  path: '/updateticket/$ticket-id',
  getParentRoute: () => rootRoute,
} as any)

const PostsIdRoute = PostsIdImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => rootRoute,
} as any)

const GetsingleticketTicketIdRoute = GetsingleticketTicketIdImport.update({
  id: '/getsingleticket/$ticket-id',
  path: '/getsingleticket/$ticket-id',
  getParentRoute: () => rootRoute,
} as any)

const GetfilesTicketIdRoute = GetfilesTicketIdImport.update({
  id: '/getfiles/$ticket-id',
  path: '/getfiles/$ticket-id',
  getParentRoute: () => rootRoute,
} as any)

const GetallcommentsTicketIdRoute = GetallcommentsTicketIdImport.update({
  id: '/getallcomments/$ticket-id',
  path: '/getallcomments/$ticket-id',
  getParentRoute: () => rootRoute,
} as any)

const FileuploadTicketIdRoute = FileuploadTicketIdImport.update({
  id: '/fileupload/$ticket-id',
  path: '/fileupload/$ticket-id',
  getParentRoute: () => rootRoute,
} as any)

const AssignticketsTicketIdRoute = AssignticketsTicketIdImport.update({
  id: '/assigntickets/$ticket-id',
  path: '/assigntickets/$ticket-id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/createticket': {
      id: '/createticket'
      path: '/createticket'
      fullPath: '/createticket'
      preLoaderRoute: typeof CreateticketImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/getStats': {
      id: '/getStats'
      path: '/getStats'
      fullPath: '/getStats'
      preLoaderRoute: typeof GetStatsImport
      parentRoute: typeof rootRoute
    }
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/signUp': {
      id: '/signUp'
      path: '/signUp'
      fullPath: '/signUp'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/singinupdatepasssword': {
      id: '/singinupdatepasssword'
      path: '/singinupdatepasssword'
      fullPath: '/singinupdatepasssword'
      preLoaderRoute: typeof SinginupdatepassswordImport
      parentRoute: typeof rootRoute
    }
    '/updatepassword': {
      id: '/updatepassword'
      path: '/updatepassword'
      fullPath: '/updatepassword'
      preLoaderRoute: typeof UpdatepasswordImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/assigntickets/$ticket-id': {
      id: '/assigntickets/$ticket-id'
      path: '/assigntickets/$ticket-id'
      fullPath: '/assigntickets/$ticket-id'
      preLoaderRoute: typeof AssignticketsTicketIdImport
      parentRoute: typeof rootRoute
    }
    '/fileupload/$ticket-id': {
      id: '/fileupload/$ticket-id'
      path: '/fileupload/$ticket-id'
      fullPath: '/fileupload/$ticket-id'
      preLoaderRoute: typeof FileuploadTicketIdImport
      parentRoute: typeof rootRoute
    }
    '/getallcomments/$ticket-id': {
      id: '/getallcomments/$ticket-id'
      path: '/getallcomments/$ticket-id'
      fullPath: '/getallcomments/$ticket-id'
      preLoaderRoute: typeof GetallcommentsTicketIdImport
      parentRoute: typeof rootRoute
    }
    '/getfiles/$ticket-id': {
      id: '/getfiles/$ticket-id'
      path: '/getfiles/$ticket-id'
      fullPath: '/getfiles/$ticket-id'
      preLoaderRoute: typeof GetfilesTicketIdImport
      parentRoute: typeof rootRoute
    }
    '/getsingleticket/$ticket-id': {
      id: '/getsingleticket/$ticket-id'
      path: '/getsingleticket/$ticket-id'
      fullPath: '/getsingleticket/$ticket-id'
      preLoaderRoute: typeof GetsingleticketTicketIdImport
      parentRoute: typeof rootRoute
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdImport
      parentRoute: typeof rootRoute
    }
    '/updateticket/$ticket-id': {
      id: '/updateticket/$ticket-id'
      path: '/updateticket/$ticket-id'
      fullPath: '/updateticket/$ticket-id'
      preLoaderRoute: typeof UpdateticketTicketIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/createticket': typeof CreateticketRoute
  '/dashboard': typeof DashboardRoute
  '/getStats': typeof GetStatsRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/singinupdatepasssword': typeof SinginupdatepassswordRoute
  '/updatepassword': typeof UpdatepasswordRoute
  '/users': typeof UsersRoute
  '/assigntickets/$ticket-id': typeof AssignticketsTicketIdRoute
  '/fileupload/$ticket-id': typeof FileuploadTicketIdRoute
  '/getallcomments/$ticket-id': typeof GetallcommentsTicketIdRoute
  '/getfiles/$ticket-id': typeof GetfilesTicketIdRoute
  '/getsingleticket/$ticket-id': typeof GetsingleticketTicketIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/updateticket/$ticket-id': typeof UpdateticketTicketIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/createticket': typeof CreateticketRoute
  '/dashboard': typeof DashboardRoute
  '/getStats': typeof GetStatsRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/singinupdatepasssword': typeof SinginupdatepassswordRoute
  '/updatepassword': typeof UpdatepasswordRoute
  '/users': typeof UsersRoute
  '/assigntickets/$ticket-id': typeof AssignticketsTicketIdRoute
  '/fileupload/$ticket-id': typeof FileuploadTicketIdRoute
  '/getallcomments/$ticket-id': typeof GetallcommentsTicketIdRoute
  '/getfiles/$ticket-id': typeof GetfilesTicketIdRoute
  '/getsingleticket/$ticket-id': typeof GetsingleticketTicketIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/updateticket/$ticket-id': typeof UpdateticketTicketIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/createticket': typeof CreateticketRoute
  '/dashboard': typeof DashboardRoute
  '/getStats': typeof GetStatsRoute
  '/signIn': typeof SignInRoute
  '/signUp': typeof SignUpRoute
  '/singinupdatepasssword': typeof SinginupdatepassswordRoute
  '/updatepassword': typeof UpdatepasswordRoute
  '/users': typeof UsersRoute
  '/assigntickets/$ticket-id': typeof AssignticketsTicketIdRoute
  '/fileupload/$ticket-id': typeof FileuploadTicketIdRoute
  '/getallcomments/$ticket-id': typeof GetallcommentsTicketIdRoute
  '/getfiles/$ticket-id': typeof GetfilesTicketIdRoute
  '/getsingleticket/$ticket-id': typeof GetsingleticketTicketIdRoute
  '/posts/$id': typeof PostsIdRoute
  '/updateticket/$ticket-id': typeof UpdateticketTicketIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/createticket'
    | '/dashboard'
    | '/getStats'
    | '/signIn'
    | '/signUp'
    | '/singinupdatepasssword'
    | '/updatepassword'
    | '/users'
    | '/assigntickets/$ticket-id'
    | '/fileupload/$ticket-id'
    | '/getallcomments/$ticket-id'
    | '/getfiles/$ticket-id'
    | '/getsingleticket/$ticket-id'
    | '/posts/$id'
    | '/updateticket/$ticket-id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/createticket'
    | '/dashboard'
    | '/getStats'
    | '/signIn'
    | '/signUp'
    | '/singinupdatepasssword'
    | '/updatepassword'
    | '/users'
    | '/assigntickets/$ticket-id'
    | '/fileupload/$ticket-id'
    | '/getallcomments/$ticket-id'
    | '/getfiles/$ticket-id'
    | '/getsingleticket/$ticket-id'
    | '/posts/$id'
    | '/updateticket/$ticket-id'
  id:
    | '__root__'
    | '/'
    | '/createticket'
    | '/dashboard'
    | '/getStats'
    | '/signIn'
    | '/signUp'
    | '/singinupdatepasssword'
    | '/updatepassword'
    | '/users'
    | '/assigntickets/$ticket-id'
    | '/fileupload/$ticket-id'
    | '/getallcomments/$ticket-id'
    | '/getfiles/$ticket-id'
    | '/getsingleticket/$ticket-id'
    | '/posts/$id'
    | '/updateticket/$ticket-id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CreateticketRoute: typeof CreateticketRoute
  DashboardRoute: typeof DashboardRoute
  GetStatsRoute: typeof GetStatsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  SinginupdatepassswordRoute: typeof SinginupdatepassswordRoute
  UpdatepasswordRoute: typeof UpdatepasswordRoute
  UsersRoute: typeof UsersRoute
  AssignticketsTicketIdRoute: typeof AssignticketsTicketIdRoute
  FileuploadTicketIdRoute: typeof FileuploadTicketIdRoute
  GetallcommentsTicketIdRoute: typeof GetallcommentsTicketIdRoute
  GetfilesTicketIdRoute: typeof GetfilesTicketIdRoute
  GetsingleticketTicketIdRoute: typeof GetsingleticketTicketIdRoute
  PostsIdRoute: typeof PostsIdRoute
  UpdateticketTicketIdRoute: typeof UpdateticketTicketIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CreateticketRoute: CreateticketRoute,
  DashboardRoute: DashboardRoute,
  GetStatsRoute: GetStatsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  SinginupdatepassswordRoute: SinginupdatepassswordRoute,
  UpdatepasswordRoute: UpdatepasswordRoute,
  UsersRoute: UsersRoute,
  AssignticketsTicketIdRoute: AssignticketsTicketIdRoute,
  FileuploadTicketIdRoute: FileuploadTicketIdRoute,
  GetallcommentsTicketIdRoute: GetallcommentsTicketIdRoute,
  GetfilesTicketIdRoute: GetfilesTicketIdRoute,
  GetsingleticketTicketIdRoute: GetsingleticketTicketIdRoute,
  PostsIdRoute: PostsIdRoute,
  UpdateticketTicketIdRoute: UpdateticketTicketIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/createticket",
        "/dashboard",
        "/getStats",
        "/signIn",
        "/signUp",
        "/singinupdatepasssword",
        "/updatepassword",
        "/users",
        "/assigntickets/$ticket-id",
        "/fileupload/$ticket-id",
        "/getallcomments/$ticket-id",
        "/getfiles/$ticket-id",
        "/getsingleticket/$ticket-id",
        "/posts/$id",
        "/updateticket/$ticket-id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/createticket": {
      "filePath": "createticket.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/getStats": {
      "filePath": "getStats.tsx"
    },
    "/signIn": {
      "filePath": "signIn.tsx"
    },
    "/signUp": {
      "filePath": "signUp.tsx"
    },
    "/singinupdatepasssword": {
      "filePath": "singinupdatepasssword.tsx"
    },
    "/updatepassword": {
      "filePath": "updatepassword.tsx"
    },
    "/users": {
      "filePath": "users.tsx"
    },
    "/assigntickets/$ticket-id": {
      "filePath": "assigntickets/$ticket-id.tsx"
    },
    "/fileupload/$ticket-id": {
      "filePath": "fileupload/$ticket-id.tsx"
    },
    "/getallcomments/$ticket-id": {
      "filePath": "getallcomments/$ticket-id.tsx"
    },
    "/getfiles/$ticket-id": {
      "filePath": "getfiles/$ticket-id.tsx"
    },
    "/getsingleticket/$ticket-id": {
      "filePath": "getsingleticket/$ticket-id.tsx"
    },
    "/posts/$id": {
      "filePath": "posts/$id.tsx"
    },
    "/updateticket/$ticket-id": {
      "filePath": "updateticket/$ticket-id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
